spring:
    mail:
      host: smtp.googlemail.com
      username: justifycontent1@gmail.com
      password: Email.123
      port: 587
      properties.mail.smtp:
                       starttls.enable: true
    datasource:
        url: jdbc:h2:~/bavaria;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
        username: sa

    jpa:
        hibernate:
            ddl-auto: update
    h2:
          console:
            enabled: true
            path: /h2-console

logging:
  level: info
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000
server:
  port: 8080

