spring:
    mail:
      host: smtp.googlemail.com
      username: justifycontent1@gmail.com
      password: Email.123
      port: 587
      properties.mail.smtp:
                       starttls.enable: true
    datasource:
        url: jdbc:h2:~/bavaria;DB_CLOSE_ON_EXIT=FALSE

    jpa:
        hibernate:
            ddl-auto: create-drop
security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
logging:
  level: info
